const studentActionTypes = {
  LOADING_STUDENTS: "LOADING_STUDENTS",
  LOADED_STUDENTS: "LOADED_STUDENTS",
  ADD_STUDENT: "ADD_STUDENT",
  EDIT_STUDENT: "EDIT_STUDENT",
  DELETE_STUDENT: "DELETE_STUDENT",
  STUDENT_ERROR: "STUDENT_ERROR",
  PROCESSING_STUDENT: "PROCESSING_STUDENT",
};

export default studentActionTypes;
