const classActionTypes = {
  LOADING_CLASSES: "LOADING_CLASSES",
  LOADED_CLASSES: "LOADED_CLASSES",
  ADD_CLASS: "ADD_CLASS",
  DELETE_CLASS: "DELETE_CLASS",
  CLASS_ERROR: "CLASS_ERROR",
  PROCESSING: "PROCESSING",
};

export default classActionTypes;
